import pyautogui
import time
time.sleep(5)
users=['e','d','c','b','a']#name of user
pyautogui.doubleClick(180,39)
time.sleep(2)
##x,y=pyautogui.position()
##print(x,y)
pyautogui.click(299 ,56)
time.sleep(2)
pyautogui.write("https://web.whatsapp.com/")
pyautogui.press('enter')
time.sleep(12)
##x,y=pyautogui.position()
##print(x,y)
for user in users:
   pyautogui.click(269,175)
   time.sleep(2)
   pyautogui.write(user)
   pyautogui.press('enter')
   time.sleep(6)
   x,y=pyautogui.position()
   print(x,y)
   pyautogui.click(684 ,665)
   pyautogui.write("good afternoon all of you today i send message through python pyautogui library")
   pyautogui.press("enter")
##time.sleep(2)
##pyautogui.write("1111111111")
##pyautogui.press("enter")
